### ISSUE TITLE
Mica and Some Button SVG Files Can't use in Firefox 117 and Up

### ISSUE THREAD

**Issue by StevenChang1892** [bmFtZQ/edge-frfox#101]
**Description**
I am experiencing the same issue as reported in the link below where the Mica effect is missing and the minimize, maximize, and close buttons for the window are all the default ones instead of using the svg files.

**Inferred Cause**
I guess it was the new update to change the rules. Maybe it deleted or changed a value `-moz-win-borderless-glass`.

> Reference link: https://github.com/bmFtZQ/edge-frfox/issues/98#issuecomment-1698402407
![Release Note](https://github.com/bmFtZQ/edge-frfox/assets/115457858/9bc55f25-4587-46d4-845c-f9ee55cf24e0)
URL: https://www.mozilla.org/en-US/firefox/117.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog

**Reproduce**
##### Buttons
After installing this theme, you will see that.

##### Mica
See this link: https://github.com/bmFtZQ/edge-frfox#mica-tweak-instructions-windows-11-only

**Include screenshot / video recording if possible.**

##### Buttons
![The Photo of The Buttons](https://github.com/bmFtZQ/edge-frfox/assets/115457858/7a308b37-8bae-4d19-aed9-0f5048f1b5b0)

##### Mica
![Mica Effect](https://github.com/bmFtZQ/edge-frfox/assets/115457858/298d620d-4132-4f81-906b-00974b888a63)
![The Wallpaper](https://github.com/bmFtZQ/edge-frfox/assets/115457858/f2fd5c1b-d1f7-485c-8e4a-717faa10dc72)
![Firefox](https://github.com/bmFtZQ/edge-frfox/assets/115457858/2cd21695-c277-4e75-8ffb-3430f4dd24da)

**Configuration**
- Firefox Version: 117.0.1
- OS: Microsoft Windows 11 22H2 Build 22621.2215

**Comment by StevenChang1892** [comment]
Buttons Reference source code: https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/icons/icons.css
```css
@media (-moz-windows-compositor),
(-moz-gtk-csd-available) {
  .titlebar-min {
    list-style-image: url("win11-minimize.svg") !important;
  }

  .titlebar-max {
    list-style-image: url("win11-maximize.svg") !important;
  }

  .titlebar-restore {
    list-style-image: url("win11-restore.svg") !important;
  }

  .titlebar-close {
    list-style-image: url("win11-close.svg") !important;
  }
```
The implementation method of Mica effect is not yet known.
