### ISSUE TITLE
Sidebar menupopup lose background-color in TreeStyleTab extension

### ISSUE THREAD

**Issue by rainbowflesh** [bmFtZQ/edge-frfox#103]
The bug looks like:
![1](https://github.com/bmFtZQ/edge-frfox/assets/20819692/65b59aa4-03a0-40ee-9920-f9dc89cc9509)

Can be fixed by delete `background` value in popup.css:
```css
...
  .popup-internal-box,
  panel[type="autocomplete-richlistbox"] > .autocomplete-richlistbox,
  .menupopup-arrowscrollbox {
/* background: var(--arrowpanel-background) !important; */
    border: 0 !important;
  }
...
```
![2](https://github.com/bmFtZQ/edge-frfox/assets/20819692/c7891b2f-2241-4e29-9e66-60c596e2f806)

What could be gone wrong with delete this parameter? 

**Configuration**
- Firefox Version: 119.0b3 (64-bit), This bug is newly in 119.
- OS: Windows, GTK
