### ISSUE TITLE
Remove/edit 1px line under navigation bar

### ISSUE THREAD

**Issue by quietrobot** [bmFtZQ/edge-frfox#107]
![imagen](https://github.com/bmFtZQ/edge-frfox/assets/87845044/0c4da133-f233-4c9d-8d7b-f62ed7516a46)

Is there a way to eliminate or change the color of this dividing line? thanks!

**Comment by bmFtZQ** [comment]
You can do this by changing the `--chrome-content-separator-color` colour variable in the `colors.css` file.

```css
:root:not(:-moz-lwtheme),
:root[privatebrowsingmode="temporary"][style*="--lwt-accent-color: rgb(28, 27, 34)"] {
  --chrome-content-separator-color: light-dark([LIGHT COLOUR], [DARK COLOUR]) !important;
}
```
or make it transparent:

```css
--chrome-content-separator-color: transparent !important;
```

**Comment by bmFtZQ** [comment]
Alternatively, you could try changing the colour of the border directly:

```css
#navigator-toolbox {
  border-bottom-color: transparent !important;
}
```

Or remove the border:
```css
#navigator-toolbox {
  border-bottom-width: 0 !important;
}
```
