### ISSUE TITLE
Broken tweaks in Firefox 120+

### ISSUE THREAD

**Issue by SafariBat** [bmFtZQ/edge-frfox#109]
**Description**
When enabling **uc.tweak.newtab-background** the background image will not display. The tweak **uc.tweak.vertical-context-navigation** also seems broken since enabling it will not make the context menu vertical. The customize Firefox page no longer displays the correct background color.

**Customize Page Tab**
![TabPage](https://github.com/bmFtZQ/edge-frfox/assets/107957769/a9a23578-7c26-4ad3-9e28-513081b209d2)

**Configuration**
- Firefox Version: 120.0
- OS: Windows 11

**Comment by bmFtZQ** [comment]
Mozilla has changed the way that preferences/tweaks are selected in CSS. Now they use `@media` rules instead of the `@support` rules they used to use.

One benefit of this change is that now tweaks can be applied and removed in real-time, without needing to restart the browser.

This should be fixed now, along with that customisation menu background colour issue.

Reference for anyone looking for the difference between them:

```css
@supports -moz-bool-pref("PREFERENCE") {
    background: red;
}
```

```css
@media (-moz-bool-pref: "PREFERENCE") {
    background: red;
}
```
