### ISSUE TITLE
Emulate mica using css blur filter.

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#115]
Could the blur filter in css be used to emulate mica for context-menus and the rest?

**Comment by bmFtZQ** [comment]
This would not be possible using the `backdrop-filter` property in CSS. For that effect to work, Firefox would need to know what pixels are behind the element, but the context menu (and other parts) are rendered as their own windows, separate from everything else. So when trying to use the filter, nothing happens.

Here is some CSS that could achieve this effect (if possible):

```css
.menupopup-arrowscrollbox {
  background-color: rgb(255 255 255 / 0.5) !important;
  backdrop-filter: blur(20px) !important;
}
```

But trying to use the CSS above results in no filter being applied:

![screenshot containing context menu](https://github.com/bmFtZQ/edge-frfox/assets/62812711/39231faf-3054-416a-8aa5-fb38135d1314)
