### ISSUE TITLE
Tab Bar Navigation Arrows Visual Bug

### ISSUE THREAD

**Issue by Tap-W** [bmFtZQ/edge-frfox#122]
### Description
The navigation arrows in the horizontal tab bar will appear and disappear whe moving the mouse or opening a new tab when the tabs list fills the bar, but doesn't overflow.

https://github.com/bmFtZQ/edge-frfox/assets/96104958/2dc5501b-663e-403c-a2fa-2c3760702e52

### Configuration
* Firefox Version: 120.0.1
* OS: Windows 10 22H2

**Comment by bmFtZQ** [comment]
This should hopefully be fixed now, but could you test it to make sure?

I think the rule below was responsible, causing Firefox to continuously recalculate the size as the last tab can be a different size in each of the two states (overflowing, not overflowing), causing the two states to alternate rapidly, and causing the flickering effect.

```css
:root:not([customizing]) #tabbrowser-arrowscrollbox[overflowing] > tab:nth-last-child(1 of .tabbrowser-tab:not([hidden])) &::after {
  content: initial !important;
}
```
