### ISSUE TITLE
Changing the density doesn't affect the size of the tabs

### ISSUE THREAD

**Issue by dhra** [bmFtZQ/edge-frfox#124]
### Description
- Open the `Customize` page on the FF
- Change the density

**Include screenshot / video recording if possible.**
[Screencast from 2023-12-22 07-55-56.webm](https://github.com/bmFtZQ/edge-frfox/assets/29132485/9a98fd4c-91a2-46cf-8c88-e0c478d06bdd)

### Configuration
* Firefox Version: 123 nightly
* OS: Ubuntu, Gnome 45.2

**Comment by bmFtZQ** [comment]
At the moment, this theme does not support any density other than 'Normal', if the tabs size is the only thing you want to change, then temporarily you can add this to the `userChrome.css` file:

```css
#titlebar {
  --tab-min-height: 32px !important;
}
```

You can then change the 32px (default size) to the size that you need.

If you want the size of the labels to be larger, then you can add this to the `userChrome.css` file:

```css {
.tabbrowser-tab {
  font-size: 12px !important;
}
```
You can then change the 12px (default size) to the size that you need.
