### ISSUE TITLE
YouTube search bar bug

### ISSUE THREAD

**Issue by atuburapaler** [bmFtZQ/edge-frfox#142]
### Description
You can replicate this error by going to Youtube.com and using the search bar. It seems to be a bug with the transparency of the round edges of this bar.

### **With theme (edge-frfox)**

![With theme](https://github.com/bmFtZQ/edge-frfox/assets/63199696/ea813baa-d7d1-4016-a917-a4ce47a6db44)

### **Without theme (Vanilla Firefox)**

![Vanilla](https://github.com/bmFtZQ/edge-frfox/assets/63199696/a6c32106-7ed2-4824-9e79-b5bcea3c1ec9)

### Configuration
* Firefox Version: 124.0.2 (20240401114208)
* OS: Windows 11 (23H2)
* Tweaks enabled: 
  * `uc.tweak.floating-tabs`
  * `uc.tweak.force-tab-colour`
  * `uc.tweak.context-menu.compact-extensions-menu`

**Comment by bmFtZQ** [comment]
For some reason, on YouTube there is an iframe behind the search suggestions (the white box) but it is never used (seemingly). Normally a blank iframe is transparent, but this rule that was applied to `about:blank` added a background colour to it:

```css
/* fix page flashes when loading some websites */
@-moz-document url(about:blank) {
  body {
    background: var(--in-content-page-background);
    color: var(--in-content-page-color);
  }
}
```

I've removed that rule now so this issue should be resolved.
