### ISSUE TITLE
Bookmark bar height configurable

### ISSUE THREAD

**Issue by heyXiaoT** [bmFtZQ/edge-frfox#148]
### Description
I modified the style in personalbar.css to make the bookmark bar compact. If possible, I hope these parameters can be configured in about: config

```css
:root {
  /* --bookmark-block-padding: 6px !important;
  --bookmark-inline-padding: 6px !important;
  --bookmark-block-margin: 2px !important;
  --bookmark-inline-margin: 2px !important;
  --uc-bookmark-toolbar-padding-bottom: 2px; */
  --bookmark-block-padding: 0px !important;
  --bookmark-inline-padding: 2px !important;
  --bookmark-block-margin: 1px !important;
  --bookmark-inline-margin: 2px !important;
  --uc-bookmark-toolbar-padding-bottom: 2px;
  --bookmarks-toolbar-overlapping-browser-height: calc(var(--uc-bookmark-toolbar-padding-bottom) + 16px + (var(--bookmark-block-margin) + var(--bookmark-block-padding)) * 2) !important;
}
```
### before and after comparison
![图片](https://github.com/bmFtZQ/edge-frfox/assets/30957584/56a4ffd5-745e-4a2a-992f-ddf744837194)
![图片](https://github.com/bmFtZQ/edge-frfox/assets/30957584/bba956dc-c7e2-4eb8-b6a5-0049e422e26c)
**Include screenshot / video recording if possible.**
