### ISSUE TITLE
Any way to make the searchbar a rounded rectangle like in other Fluent Design apps?

### ISSUE THREAD

**Issue by kamez104** [bmFtZQ/edge-frfox#162]
![obraz](https://github.com/user-attachments/assets/8fabe028-7ac9-41c1-9753-7dc56ea57e09)
![obraz](https://github.com/user-attachments/assets/53d603a3-3d4d-48fd-ac6e-f85344d434b0)
![obraz](https://github.com/user-attachments/assets/0229c175-3fa7-4b68-8cbe-31e504fc27d4)

**Comment by bmFtZQ** [comment]
You can adjust the border-radius of the URL bar using a rule like this in `userChrome.css` or `custom.css`:

```css
:root {
  /* Adjust URL bar corner radius. */
  --urlbar-icon-border-radius: 8px !important;

  /* Adjust padding on the left and right of URL bar. */
  --uc-urlbar-inline-padding: 1px !important;
}
```
