### ISSUE TITLE
Add blurred right click menu

### ISSUE THREAD

**Issue by nonetrix** [bmFtZQ/edge-frfox#58]
**Description**
Add blur to right click menu this requires ```layout.css.backdrop-filter.enabled``` to be set to true on older versions of Firefox it was only recently enabled by default as of 103 to my knowledge maybe 102-101?

**Include screenshot / video recording if possible.**

![Screenshot 2022-07-29 203312](https://user-images.githubusercontent.com/45698918/181865212-cdc7b260-63d4-44be-a3b7-913f1d303f16.png)

**Comment by EdwardLangdon** [comment]
It is set to true for me but I don't see the blur effect. Do you use Mica ?

**Comment by nonetrix** [comment]
I am on Windows 11 I assume so

**Comment by bmFtZQ** [comment]
It seems that `backdrop-filter` cannot be applied to the context menu. I think it is because Firefox draws context menus as their own windows separate from other content, but Firefox can only blur it's own in-page content.

```css
.menupopup-arrowscrollbox {
  background: #fff8 !important;
  backdrop-filter: blur(20px) !important;
}
```

![screen shot](https://user-images.githubusercontent.com/62812711/182785392-a1af3f17-3dbc-4699-8630-e00f4b95b134.png)

`backdrop-filter` is definitely enabled: 

```css
body {
  backdrop-filter: blur(20px) !important;
}
```

![backdrop-filter test](https://user-images.githubusercontent.com/62812711/182786248-4faa88d0-6350-4fce-8b3c-0c271b945aad.png)
