### ISSUE TITLE
(NEW) Edge-like search bar

### ISSUE THREAD

**Issue by Hidetoshi6721** [bmFtZQ/edge-frfox#69]
**Description**
The new Edge search bar is more rounded and feels kinda more soothing :3
Can we have it in the userchrome?

**Include screenshot / video recording if possible.**
![image](https://user-images.githubusercontent.com/85873175/208234232-b97fe88c-a465-44d2-9013-04c77a855113.png)

**Comment by DanielSGH** [comment]
I know this issue is old, but if anyone still wants to do this, all you have to do is play around with the right operand in this calculation:

In **urlbar.css**, see permalink below
```css
#urlbar-background,
#searchbar {
  border-radius: calc(var(--toolbarbutton-border-radius) + 2px) !important; /* change `2px` here to ~20px or something */
}
```

https://github.com/bmFtZQ/edge-frfox/blob/b97704db54f6230da5aeeec8a1d5ac6038b42880/chrome/toolbar/urlbar.css#L119
